services:
  - type: web
    name: doctor-hub
    runtime: node
    plan: free
    buildCommand: npm ci && npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
